Remove directory view and test report publishing steps
Removed steps to view the current directory and publish test report.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,15 +34,15 @@ jobs:
       - name: Run JUnit tests
         run: |
           java -cp out:junit-platform-console-standalone-6.0.2.jar org.junit.platform.console.ConsoleLauncher execute --classpath out --select-class test.AllTests 
-      - name: View current Directory
-        run: |
-          echo "Contents of current directory:"
-          ls -R
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v6.4.0
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: 'report/*.xml'
+#      - name: View current Directory
+#        run: |
+#          echo "Contents of current directory:"
+#          ls -R
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v6.4.0
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          report_paths: 'report/*.xml'
       - name: Upload Test Report Artifact
         uses: actions/upload-artifact@v6
         with:
