Update GitHub Actions workflow for testing
Using:

https://github.com/marketplace/actions/junit-report-action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,19 +8,15 @@ on:
 
 jobs:
   build:
+    name: Build and Run Tests
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up JDK 11
-        uses: actions/setup-java@v1
+      - name: Checkout Code
+        uses: actions/checkout@v4
+      - name: Build and Run Tests
+        run: # execute your tests generating test results
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
         with:
-          java-version: '11'
-
-      - name: Build with Gradle
-        run: ./gradlew build
-
-      - name: Run tests
-        run: ./gradlew test
+          report_paths: '**/build/test-results/test/TEST-*.xml'
