Add step to publish test report in workflow
Re-inserted mikepenz  action-junit-report

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,6 +38,11 @@ jobs:
         run: |
           echo "Contents of current directory:"
           ls -R
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6.4.0
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'report/*.xml'
       - name: Upload Test Report Artifact
         uses: actions/upload-artifact@v6
         with:
